version: "3.4"
# broker-frontend-public
services:
  apache:
    image: 666509747749.dkr.ecr.eu-west-1.amazonaws.com/broker-frontend-public:latest$GitCommitAppendix
    environment:
      ENV_TYPE: "testserver"
    volumes:
      - /srv/local/broker-frontend-public/test:/var/log/apache2
    ports:
      - 11112:80
    # networks:
      # - test
    stop_grace_period: 60s
    stop_signal: WINCH
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        parallelism: 1
        delay: 40s
        max_failure_ratio: 1
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 256M
      placement:
        constraints:
          - 'node.labels.COUNTRY_poland == TRUE'
          - 'node.labels.SITE_PUBLIC == TRUE'
          - 'node.labels.ENV_TEST == TRUE'

  redis:
    image: redis:latest
    # networks:
      # - test
    stop_grace_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 70s
        max_failure_ratio: 1
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 30
        window: 30s
      resources:
        limits:
          memory: 64M
      placement:
        constraints:
          - 'node.labels.COUNTRY_poland == TRUE'
          - 'node.labels.SITE_PUBLIC == TRUE'
          - 'node.labels.ENV_TEST == TRUE'

# networks:
  # default:
    # driver: overlay
  # test:
    # driver: overlay
